package com.github.dlna;

import android.os.Build;

import org.fourthline.cling.model.types.UDN;

import java.util.UUID;

public class Utils {
    public static final String MANUFACTURER = android.os.Build.MANUFACTURER;
    public static final String DMR_NAME = "MSI MediaRenderer";

    public static final String DMR_DESC = "MSI MediaRenderer";
    public static final String DMR_MODEL_URL = "http://4thline.org/projects/cling/mediarenderer/";

    public static UDN uniqueSystemIdentifier() {
        String salt = "msidmr";
        StringBuilder systemSalt = new StringBuilder();
        systemSalt.append(getUUID());
        systemSalt.append(Build.MODEL);
        systemSalt.append(Build.MANUFACTURER);
        return new UDN(new UUID(Long.MAX_VALUE, salt.hashCode()));
    }

    public static String getRenderName() {
        return "Cling Test Local Render";
    }

    public static String getUUID() {
        // Random uuid generated by openssl, just for test
        return "PJqQPF+Zfdi1T50Lncs=";
    }
}
